### ISSUE TITLE
Stack smashing detected when running dpkg

### ISSUE THREAD

**Issue by fridex** [thoth-station/package-extract#271]
**Describe the bug**
Try to analyze `python:3.6` based container image (which is debian based). When running the analysis I get "stack smashing detected" error.

**To Reproduce**
1. Go to user-api
2. Trigger package-extract endpoint with `python:3.6` based container image
3. See the error produced by package-extract

**Expected behavior**

The given container image should be analyzed by package-extract.

**Additional context**

```
2019-08-05 14:00:34,849 [1] INFO     root:119: Setting up logging to a Sentry instance 'sentry.io/1298083', environment thoth-test-core
--
  | 2019-08-05 14:00:34,854 [1] INFO     root:150: Logging to rsyslog endpoint is turned off
  | 2019-08-05 14:01:47,225 [1] CRITICAL root:111: Traceback (most recent call last):
  | File "/usr/local/bin/thoth-package-extract", line 11, in <module>
  | load_entry_point('thoth-package-extract==1.0.1', 'console_scripts', 'thoth-package-extract')()
  | File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "/usr/local/lib64/python3.6/site-packages/click/decorators.py", line 17, in new_func
  | return f(get_current_context(), *args, **kwargs)
  | File "/usr/local/lib/python3.6/site-packages/thoth_package_extract-1.0.1-py3.6.egg/thoth/package_extract/cli.py", line 164, in cli_extract_image
  | tls_verify=not no_tls_verify,
  | File "/usr/local/lib/python3.6/site-packages/thoth_package_extract-1.0.1-py3.6.egg/thoth/package_extract/core.py", line 79, in extract_image
  | result = run_analyzers(rootfs_path)
  | File "/usr/local/lib/python3.6/site-packages/thoth_package_extract-1.0.1-py3.6.egg/thoth/package_extract/image.py", line 450, in run_analyzers
  | deb_packages = _run_dpkg_query(path, timeout=timeout)
  | File "/usr/local/lib/python3.6/site-packages/thoth_package_extract-1.0.1-py3.6.egg/thoth/package_extract/image.py", line 149, in _run_dpkg_query
  | output = run_command(cmd, timeout=timeout).stdout
  | File "/usr/local/lib/python3.6/site-packages/thoth/analyzer/command.py", line 108, in run_command
  | raise CommandError(error_msg, command=command, is_json=is_json)
  | thoth.analyzer.command.CommandError: Command exited with non-zero status code (134): *** stack smashing detected ***: <unknown> terminated
  | /usr/sbin/chroot.fakechroot: line 105:    80 Aborted                 env -u FAKECHROOT_BASE_ORIG FAKECHROOT_CMD_ORIG= LD_LIBRARY_PATH="$fakechroot_chroot_paths" FAKECHROOT_BASE="$fakechroot_chroot_base" "$fakechroot_chroot_chroot" "${@:1:$(($fakechroot_chroot_n - 1))}" "${fakechroot_chroot_newroot#$FAKECHROOT_BASE_ORIG}"
```

Dockerfile used to generate the container image:

```dockerfile
FROM python:3.6

RUN pip install tensorflow==1.14.0
```

**Comment by fridex** [comment]
CC @bissenbay

**Comment by fridex** [comment]
> > CC @bissenbay
> 
> @fridex This seems incompatibily of `fakechroot` when used with debian packages https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847986. It looks like we need the same version of libc6 inside and outside of the (fake)chroot in order it to work correctly. Then seems the change needs to happen on the base image.

Thanks for investigation! Sounds reasonable!

**Comment by goern** [comment]
Shall we turn this into a feature request?

**Comment by goern** [comment]
ping

**Comment by bissenbay** [comment]
> Shall we turn this into a feature request?

What does it entail?

**Comment by goern** [comment]
@fridex is this still valid?

**Comment by fridex** [comment]
Let's keep debian packages experimental and focus on RPM. The issue is documented here and can be closed.

/close
